### PR TITLE
New logo and theme

### PR DESCRIPTION
**Pull request by roket1428**
Website
scr1
scr2

Browser addon icons
addon-icon-preview

### CODE REVIEW

**Comment by simonfrey** [comment]
Closes #38

**Comment by simonfrey** [comment]
Awesome work so far. Could you maybe give the "Get Browser Extension" box a bit more styling so it pops more? :smile: 

IMO it's important to get new users on the browser extension to automatically protect them. Making the box a bit more "pushy"/styled we may archive that :D

**Comment by roket1428** [comment]
scr1
scr2

**Comment by roket1428** [comment]
Changed box design
Added hover effect to box
Added favicon
Changed default button & anchor color
Indent fix

**Pull request merged**
