### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by billcobbler**
Implements #18

### CODE REVIEW

**Comment by simonfrey** [comment]
When I execute the given instructions, I get the error: 
``` $ docker --rm --name unlink -p 8080:8080 test/unshort 
unknown flag: --rm
See 'docker --help'.```

**Comment by billcobbler** [comment]
Haha good catch, just pushed the fix.

**Comment by simonfrey** [comment]
Sorry, maybe it's me just not being able to work with docker, but I exactly followed the updated instructions and after the build I can not run it:
```
l1am0:unshort/ (dockerize) $ cd server                                        [12:52:15]

l1am0:server/ (dockerize) $ docker build -t test.unshort .                         [12:52:21]
Sending build context to Docker daemon  882.7kB
Step 1/9 : FROM golang:alpine AS build
 ---> caaf68df625f
Step 2/9 : RUN apk --no-cache add curl build-base gcc
 ---> Using cache
 ---> f45a0e435006
Step 3/9 : ADD . /src
 ---> f9909afecbef
Step 4/9 : WORKDIR /src
 ---> Running in ab6b98f5ddb5
Removing intermediate container ab6b98f5ddb5
 ---> f4558150e662
Step 5/9 : RUN go generate ./... && go generate ./db/db.go && GOOS=linux go build -o app
 ---> Running in 00f1250c68c1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/sirupsen/logrus v1.4.2
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/sirupsen/logrus v1.4.2
go: finding github.com/jmoiron/sqlx v1.2.0
go: finding github.com/mattn/go-sqlite3 v2.0.2+incompatible
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: extracting github.com/sergi/go-diff v1.1.0
go: downloading github.com/jmoiron/sqlx v1.2.0
go: downloading github.com/mattn/go-sqlite3 v2.0.2+incompatible
go: extracting github.com/jmoiron/sqlx v1.2.0
go: extracting golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: extracting github.com/mattn/go-sqlite3 v2.0.2+incompatible
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.9M  100 11.9M    0     0   488k      0  0:00:24  0:00:24 --:--:--  509k
go: finding github.com/programmfabrik/esc v0.2.5
go: downloading github.com/programmfabrik/esc v0.2.5
go: extracting github.com/programmfabrik/esc v0.2.5
go: downloading golang.org/x/tools v0.0.0-20190925020647-22afafe3322a
go: extracting golang.org/x/tools v0.0.0-20190925020647-22afafe3322a
go: finding github.com/pkg/errors v0.8.1
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20200110213125-a7a6caa82ab2
go: extracting golang.org/x/tools v0.0.0-20200110213125-a7a6caa82ab2
go: finding golang.org/x/tools latest
go: finding github.com/sergi/go-diff v1.1.0
go: finding github.com/sirupsen/logrus v1.4.2
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
Removing intermediate container 00f1250c68c1
 ---> f70a114c36c1
Step 6/9 : FROM alpine
 ---> 961769676411
Step 7/9 : WORKDIR /app
 ---> Using cache
 ---> 73c1fb2d9704
Step 8/9 : COPY --from=build /src/app /app/
 ---> 6320a045c256
Step 9/9 : ENTRYPOINT ["./app"]
 ---> Running in b47a3742e806
Removing intermediate container b47a3742e806
 ---> b698bdcb2e49
Successfully built b698bdcb2e49
Successfully tagged test.unshort:latest

l1am0:server/ (dockerize) $ docker run --rm --name unlink -p 8080:8080 test/unshort
Unable to find image 'test/unshort:latest' locally
docker: Error response from daemon: pull access denied for test/unshort, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
Assuming that I am not the only docker newbie out there, maybe more in-depth documentation would be nice :dagger:

**Comment by Jakob-em** [comment]
There is a typo in the Readme:
The image is build with the tag `test.unshort`
But then you try to run the image with the name `test/unshort`, which doesn't exist.
So decide on which tag to use in the Readme

**Comment by billcobbler** [comment]
Fixed the typo.

**Pull request merged**
