### PR TITLE
Added code in the "show.html" page to catch the enter press instead of click on the button

### PR DESCRIPTION
**Pull request by EsmailELBoBDev2**
Maybe my way of solving this problem kinda stupid but it's like literally first pull request i do (as code not translate) so bear with me 😂

### CODE REVIEW

**Comment by simonfrey** [comment]
Hey @EsmailELBoBDev2 thank you for proposing this change. 

I wonder if this not does actually does harm to the user as automatically pressing enter when they see the unshort.link page will be in muscle memory quite fast. The whole point of unshort.link is to show you the url behind the short link if you click enter right away this security measure is gone.

May I propose you to select auto redirect in the web extension if you do not want to click on the unshort.link page?

What is your take on that, do you think the muscle memory argument is valid?

**Comment by simonfrey** [comment]
Additionally: You write that's your first PR so congratulation to that!

To be honst, your commit messages are not optimal they should describe what the change does e.g. `Add javascript hook to catch enter key event and press redirect button` instead of `press enter, i hate clicking!`

And as you are in a feature branch, please use interactive git rebase to clean it ub (e.g. change the commit messages and combine the three commits into one). I learned it with the following youtube tutorial: https://www.youtube.com/watch?v=ElRzTuYln0M

**Comment by EsmailELBoBDev2** [comment]
Thanks! and for me i was just lazy to press each time so i added it? also yeah i was just happy that it was my first one and  i typed anything then i changed the tittle as you see to make it more clear and last but not least, i can just delete all of this pull request and re-open it and it going to count as one ?

**Comment by simonfrey** [comment]
Reconsidered this and I think the feature is not a good idea. Thanks for submitting, but will not merge it

**Pull request closed without merging**
